---
- hosts: cdh_servers
  remote_user: <admin user>
  become: true
  become_method: sudo

  tasks:
    - service:
        name: td-agent
        state: stopped
    - copy:
        src: ../FluentD/td-agent.conf
        dest: /etc/td-agent/td-agent.conf

 # Run the setup playbook 
- import_playbook: playbook.setup.yml